import type { FormValues } from '../types';

// Mismo set de datos de prueba con el que se validó el generador AcroForm,
// usado por el Editor de Plantilla para "Mostrar datos de prueba" y
// "Generar PDF de prueba". A propósito NO incluye valores para firma/huella:
// esos espacios deben quedar siempre vacíos.
export const SAMPLE_TEST_DATA: FormValues = {
  tipoSolicitud: 'tipoSolicitud_credito',
  calidad: 'calidad_titular',
  fechaDiligenciamiento_dia: '27',
  fechaDiligenciamiento_mes: '08',
  fechaDiligenciamiento_anio: '2026',
  vendedor: 'Juan Perez',
  concesionario: 'Automarcali S.A.S',
  primerNombre: 'JOSE',
  segundoNombre: 'ALBERTO',
  primerApellido: 'TORRES',
  segundoApellido: 'MOSQUERA',
  fechaNacimiento_dia: '15',
  fechaNacimiento_mes: '04',
  fechaNacimiento_anio: '1990',
  tipoDocumento: 'tipoDocumento_cc',
  numeroIdentificacion: '1094567890',
  lugarNacimiento_ciudad: 'Cali',
  lugarNacimiento_pais: 'Colombia',
  segundaNacionalidad: 'segundaNacionalidad_no',
  estadoCivil: 'Soltero',
  sexo: 'sexo_m',
  direccion: 'Calle 5 # 38-120 Apto 302',
  ciudad: 'Cali',
  departamento: 'Valle del Cauca',
  telefono: '6023334455',
  celular: '3001234567',
  tipoVivienda: 'tipoVivienda_familiar',
  email: 'jose.torres@example.com',
  tiempoAntiguedadDomicilio: '5 anios',
  ocupacion: 'ocupacion_empleado',
  profesion: 'Ingeniero',
  actividadEconomicaCIIU: '6201',
  empresa: 'Tech Solutions S.A.S',
  tipoContrato: 'Indefinido',
  antiguedadMeses: '36',
  cargo: 'Analista',
  sectorEconomico: 'Tecnologia',
  direccionOficinaPrincipal: 'Av 6N #23-45',
  barrio: 'Centro',
  telefonoExt: '6021234567',
  fax: '6021234568',
  ciudadOficina: 'Cali',
  gozaReconocimiento: 'gozaReconocimiento_no',
  administraRecursos: 'administraRecursos_no',
  personaPublica: 'personaPublica_no',
  detentaPoder: 'detentaPoder_no',
  transaccionesMonedaExt: 'transaccionesMonedaExt_no',
  tipoProducto: 'Vehiculo particular',
  paisProducto: 'Colombia',
  ciudadProducto: 'Cali',
  monedaProducto: 'COP',
  identificacionProducto: 'Sedan 2024',
  entidadProducto: 'Banco de Occidente',
  montoMensualProducto: '1500000',
  propiedad_tipoBien_1: 'Apartamento',
  propiedad_direccion_1: 'Calle 10 #5-20',
  propiedad_ciudad_1: 'Cali',
  propiedad_pctParticipacion_1: '100%',
  propiedad_valorBien_1: '250000000',
  conyuge_nombres: 'Maria Fernanda',
  conyuge_apellidos: 'Lopez Diaz',
  conyuge_fechaNac_dia: '20',
  conyuge_fechaNac_mes: '06',
  conyuge_fechaNac_anio: '1992',
  conyuge_tipoDoc: 'conyuge_tipoDoc_cc',
  conyuge_noIdentificacion: '1098765432',
  conyuge_sexo: 'conyuge_sexo_f',
  conyuge_email: 'maria.lopez@example.com',
  conyuge_direccion: 'Calle 5 # 38-120',
  conyuge_ciudad: 'Cali',
  conyuge_telefono: '6023334455',
  conyuge_celular: '3009876543',
  vehiculo_marca_1: 'Chevrolet',
  vehiculo_tipo_1: 'Sedan',
  vehiculo_modelo_1: '2020',
  vehiculo_placa_1: 'ABC123',
  refPersonal1_nombres: 'Jorge Ramirez',
  refPersonal1_ciudad: 'Cali',
  refPersonal1_antiguedad: '10 anios',
  refPersonal1_telefono: '3011234567',
  refPersonal1_celular: '3011234567',
  refPersonal1_relacion: 'Amigo',
  totalActivos: '400000000',
  totalPasivos: '30000000',
  totalPatrimonio: '370000000',
  ingreso_salario: '4500000',
  egreso_hipotecaArriendo: '1200000',
  ingreso_comisiones: '500000',
  egreso_tarjetasCredito: '300000',
  totalIngresos: '5000000',
  totalEgresos: '1500000',
  detalleOtrosIngresos: 'Arriendo de un local comercial',
  conc_marca: 'Chevrolet',
  conc_precioVenta: '80000000',
  conc_modelo: 'Onix 2024',
  conc_cuotaInicial: '10000000',
  conc_tipo: 'Sedan',
  conc_valorFinanciar: '70000000',
  conc_plazo: '60 meses',
  conc_tasa: '1.2% MV',
  conc_plan: 'Tradicional',
  conc_totalFinanciar: '85000000',
  conc_condicion: 'conc_nuevo',
  conc_uso: 'conc_particular',
  declA: 'declA_no',
  declB: 'declB_no',
  declC: 'declC_no',
  declD: 'declD_no',
  autorizacionEntidad: 'Banco de Occidente S.A.',
  firma_dias: '27',
  firma_mes: 'agosto',
  firma_anio: '2026',
  firma_ciudad: 'Cali',
};

/** ids de campos que NUNCA deben recibir datos de prueba (firma/huella físicas). */
export const NEVER_TEST_FIELDS: string[] = [];
